### ISSUE TITLE
Add automatic broken link checker

### ISSUE THREAD

**Issue by OctopusET** [innovationacademy-kr/hitchhikers_guide#33]
For the convenience of checking broken link. adding CI seems to be useful.

Reference:
https://github.com/awesome-selfhosted/awesome-selfhosted/blob/0cdbe4c738e5136ea5d6573945735c8acec1c38a/Makefile#L23
https://github.com/becheran/mlc

**Comment by minsuklee** [comment]
Yes, we will consider to use the tool. thanks,

**Comment by OctopusET** [comment]
Thank you for considering, 
I'm now trying to add those tool. But, shouldn't this issue be opened? I want to solve out this issue. 

If it's done I will summit PR.
